#!/usr/bin/env bash
#
# Start / Stop the dockbert "traefik" service
#
set -e

COMMAND="${1:-help}"

#
# Check the file "dockbert.env"
#
DOCKBERT_ENV=${HOME}/dockbert.env

if [ -f "$DOCKBERT_ENV" ]; then
  echo "Found dockbert.env and use it"
  source $DOCKBERT_ENV
fi


if [ ! "${COMMAND}" = "help" ]; then
  MISSING=0
  for ENV_VAR in DOCKBERT_DOMAIN DOCKBERT_USERS_FILE DOCKBERT_ACME_EMAIL DOCKBERT_ACME_PATH  ; do
    # Check Environment Variables
    if [[ -n ${ENV_VAR} ]]; then
      echo "[Error] missing the environment ${ENV_VAR}"
      MISSING=1
    fi
  done

  if [ $MISSING = 1 ]; then
    exit 1;
  fi
fi

case $COMMAND in
  'debug')
    echo "start the dockbert traefik. Stop with Crl+C"
    docker-compose up
    ;;
  'start')
    echo "start dockbert traefik in background"
    docker-compose up -d
    ;;
  'stop')
    echo "stop the dockbert traefik"
    docker-compose down
    ;;
  'help')
    echo ''
    echo '> Start / Stop the dockbert "traefik" service'
    echo ''
    echo '> Usage:'
    echo '  dockbert (start|stop|debug)'
    echo ''
    echo '  "start"   start the dockbert traefik in the background'
    echo '  "stop"    stop the dockbert traefik'
    echo '  "debug"   start the dockbert traefik. Stop with Crl+C'
    ;;
esac
