#!/usr/bin/env bash
#
# Start / Stop the dockbert "traefik" service
#

COMMAND="${1:-help}"

#
# Check the file "dockbert.env"
#
DOCKBERT_ENV=${HOME}/dockbert.env

if [ -f "${DOCKBERT_ENV}" ]; then
  echo "Found dockbert.env and use it"
  source ${DOCKBERT_ENV}
fi


if [ "${COMMAND}" != "help" ]; then
  MISSING=0

  if [[ -z "${DOCKBERT_DOMAIN}" ]]; then
    echo "[Error] missing the environment 'DOCKBERT_DOMAIN'"
    MISSING=1
  fi;
  if [[ -z "${DOCKBERT_USERS_FILE}" ]]; then
    echo "[Error] missing the environment 'DOCKBERT_USERS_FILE'"
    MISSING=1
  fi;
  if [[ -z "${DOCKBERT_ACME_EMAIL}" ]]; then
    echo "[Error] missing the environment 'DOCKBERT_ACME_EMAIL'"
    MISSING=1
  fi;
  if [[ -z "${DOCKBERT_ACME_PATH}" ]]; then
    echo "[Error] missing the environment 'DOCKBERT_ACME_PATH'"
    MISSING=1
  fi;

  if [ ${MISSING} = 1 ]; then
    exit 1;
  fi
fi

case $COMMAND in
  'debug')
    echo "start the dockbert traefik. Stop with Crl+C"
    docker-compose up
    ;;
  'start')
    echo "start dockbert traefik in background"
    docker-compose up -d
    ;;
  'stop')
    echo "stop the dockbert traefik"
    docker-compose down
    ;;
  'help')
    echo ''
    echo '> Start / Stop the dockbert "traefik" service'
    echo ''
    echo '> Usage:'
    echo '  dockbert (start|stop|debug)'
    echo ''
    echo '  "start"   start the dockbert traefik in the background'
    echo '  "stop"    stop the dockbert traefik'
    echo '  "debug"   start the dockbert traefik. Stop with Crl+C'
    ;;
esac
