#
# Dockbert "Traefik" service
#
version: '3.5'

services:
  traefik:
    image: 'traefik:latest'
    container_name: '${DOCKBERT_CONTAINER_NAME:-dockbert-traefik}'
    restart: "unless-stopped"
    command:
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--global.sendAnonymousUsage=false"
      - "--pilot.dashboard=false"
      - "--certificatesResolvers.myresolver.acme.email=${DOCKBERT_ACME_EMAIL}"
      - "--certificatesResolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesResolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesResolvers.myresolver.acme.httpchallenge.entrypoint=web"
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${DOCKBERT_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/users.passwd"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKBERT_USERS_FILE}:/etc/users.passwd"
      - "${DOCKBERT_ACME_PATH}:/etc/traefik/acme"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - dockbert-net


#
# Networks
#
# - bsf-net: Listen for the traefik edge router
#
# Command:
#   docker network create dockbert-net
#   docker network ls
# Output
# NETWORK ID     NAME           DRIVER    SCOPE
# xxxxxxxxxxxx   dockbert-net   bridge    local
#

networks:
  dockbert-net:
    driver: bridge
    external: true
